#!/usr/bin/env python3

import os
import time

core_path_ext = os.path.join(os.path.dirname(os.path.abspath(__file__)) , 'mate_src')

import sys, csv, itertools, math, platform, random
import numpy as np
from scipy.interpolate import interp1d, griddata
from scipy import optimize
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.collections import PatchCollection
import matplotlib.colors as colors
import matplotlib.cbook as cbook
from mtpy.utils import gis_tools as gis_tools

#Importing external functions

sys.path.append(core_path_ext)

from cond_models.dry_odd import * #Dry conductivity of NAMS with specialized functions
from cond_models.ol_wet_odd import * #Whole models of olivine with specialized functions
from cond_models.ol_diffusion import * #Hydrogen diffusion functions of olivine
from cond_models.opx_wet_odd import * #Whole models of opx with specialized functions
from cond_models.opx_diffusion import * #Hydrogen diffusion functions of opx
from cond_models.cpx_wet_odd import * #Whole models of cpx with specialized functions
from cond_models.cpx_diffusion import * #Hydrogen diffusion functions of cpx
from cond_models.gt_wet_odd import * #Whole models of garnet with specialized functions
from cond_models.gt_diffusion import * #Hydrogen diffusion functions of garnet
from cond_models.pl_odd import * #Conductivity functions of phlogopites
from cond_models.amp_odd import * #Conductivity functions of amphiboles
from cond_models.sp_chr_odd import * #Conductivity functions of spinel-chromites
from min_sol.ol_sol import * #Olivine solubility models

warnings.filterwarnings("ignore", category=RuntimeWarning) #ignoring many RuntimeWarning printouts that are useless


class MATE_batch(object):

	def __init__(self, core_path = core_path_ext):

		pass
